---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url:
sections:
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
instant_preview: true
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
